package sonia.app.qrsmartcard.ui;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Thorsten Ludewig <t.ludewig@ostfalia.de>
 */
public class BaseFrame extends javax.swing.JFrame
{

  private final static Logger LOGGER = LoggerFactory.getLogger(
    BaseFrame.class.getName());
  
  /**
   * Creates new form BaseFrame
   */
  public BaseFrame()
  {
    viewPort = ViewPort.getInstance();
    viewPort.setBackground(new java.awt.Color(117, 192, 255));
    viewPort.setMaximumSize(new java.awt.Dimension(800, 480));
    viewPort.setPreferredSize(new java.awt.Dimension(800, 480));
    viewPort.setSize(new java.awt.Dimension(800, 480));
    viewPort.setVerifyInputWhenFocusTarget(false);
    getContentPane().add(viewPort, java.awt.BorderLayout.CENTER);
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private ViewPort viewPort;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
